baseurl = "https://zjh.asia/tech"
title = "技术博客 - 张景赫"
languageCode = "zh-cn"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author] # Used in authorbox
  name = "张景赫"
  bio = "John Doe's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
  avatar = "https://mysite-bucket.oss-cn-wulanchabu.aliyuncs.com/avator/zjh_rectangle.jpg?x-oss-process=style/small_size_rule"

[Params]
  highlightColor = "#FF7F50"
  description = "你好" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = false
  pager = true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["post", "docs"]

[Params.logo]
  title = "技术博客"
  subtitle = "" # Logo subtitle
  image = "" 

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["recent", "taglist"]

[Params.widgets.social]
  cached = false # activate cache if true
  # Enable parts of social widget
  email = "jinghe.zhang@hotmail.com"
  facebook = ""
  twitter = ""
  instagram = ""
  linkedin = ""
  telegram = ""
  github = "VenusXK"
  gitlab = "VenusXK"
  bitbucket = ""


[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)
