############################
## CHANGE THESE
############################

baseURL: 'https://zjh.asia/aboutme/'
title: 'J.H. ZHANG'

############################
## MODULES
############################

# module:
  # imports:
    # - path: 

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'
