############################
## Author
############################

author:
  name: "Jinghe Zhang"
  image: zjh_riding.jpg
  greeting: "石油大学本科生"
  icon: ":sunglasses:"

############################
## Links
############################

links:
  - leetcode: https://leetcode.cn/u/venusxk6214/
  - github: https://github.com/VenusXK
  - weibo: https://weibo.com/u/5535319573
  # - steam: https://steamcommunity.com/id/venusxk6214
  # - wechat: https://zjh.asia/aboutme/wechat.html
  - bilibili: https://space.bilibili.com/12034135
  # - email: jinghe.zhang@hotmail.com

  # - rgate: https://github.com/chrede88/L1nkr
  # - gitlab: https://github.com/chrede88/L1nkr
  # - facebook: https://github.com/chrede88/L1nkr
  # - x-twitter: https://github.com/chrede88/L1nkr
  # - mastodon: https://github.com/chrede88/L1nkr
  # - linkedin: https://github.com/chrede88/L1nkr
  # - instagram: https://github.com/chrede88/L1nkr
  # - reddit: https://github.com/chrede88/L1nkr
  # - telegram: https://github.com/chrede88/L1nkr
  # - whatsapp: https://github.com/chrede88/L1nkr
  # - signal: https://github.com/chrede88/L1nkr
  # - codepen: https://github.com/chrede88/L1nkr
  # - dev: https://github.com/chrede88/L1nkr
  # - website: https://github.com/chrede88/L1nkr
  # - link: https://github.com/chrede88/L1nkr
  # - discord: https://github.com/chrede88/L1nkr
  # - orcid: https://github.com/chrede88/L1nkr
  # - slack: https://github.com/chrede88/L1nkr
  # - stack-overflow: https://github.com/chrede88/L1nkr
  # - twitch: https://github.com/chrede88/L1nkr
  # - patreon: https://github.com/chrede88/L1nkr
  # - soundcloud: https://github.com/chrede88/L1nkr
  # - dribbble: https://github.com/chrede88/L1nkr
  # - stack-exchange: https://github.com/chrede88/
  # - tiktok: https://github.com/chrede88/
  # - youtube: https://github.com/chrede88/
  # - keybase: https://github.com/chrede88/
  # - flickr: https://github.com/chrede88/
  # - tumblr: https://github.com/chrede88/
  # - kickstarter: https://github.com/chrede88/
  # - snapchat: https://github.com/chrede88/
  # - bluesky: https://bsky.app
  # - bitbucket: https://github.com/chrede88/
  # - bandcamp: https://github.com/chrede88/
  # - etsy: https://github.com/chrede88/
  # - spotify: https://github.com/chrede88/
  # - pinterest: https://github.com/chrede88/
  # - strava: https://github.com/chrede88/
  # - untappd: https://github.com/chrede88/
  # - skype: https://github.com/chrede88/
  # - medium: https://github.com/chrede88/
  # - foursquare: https://github.com/chrede88/
  # - apple: https://github.com/chrede88/
  # - amazon: https://github.com/chrede88/
  # - google: https://github.com/chrede88/
  # - paypal: https://github.com/chrede88/
  # - windows: https://github.com/chrede88/

############################
## Colunms of Links
############################

# between 2 & 6 columns are supported (both incl)
columns: 2

###############################
## OpenGraph & Twitter Cards
###############################

title: "xx"
description: "xx"
images:
  # - IMG_20231021_143315.jpg